### ISSUE TITLE
HEAD method request return 404 error

### ISSUE THREAD

**Issue by chillin0531** [thecatalinstan/Criollo#108]
For HEAD method request we are getting 404 error response from server. 
Is any configuration/settings needs to be updated to accept HEAD requests.
I'm just starting the server with 'startListening' method alone. 

For the same request the GET method works.

**Comment by thecatalinstan** [comment]
Are you adding any routes? If not, then the server will only return 404.

To add a route for `HEAD` you could do something like:

```swift
server.head("/") { (_, res, _) in
  res.send("Hello world!")
}
```

If you want to add the route for all HTTP methods, use `.add` instead of `.head`.

I tried to write some examples at some point just to make it easier to get started. Have a look at [https://github.com/thecatalinstan/Criollo/tree/1.1.0/Examples](https://github.com/thecatalinstan/Criollo/tree/1.1.0/Examples).

Hope this helps!

**Comment by chillin0531** [comment]
@thecatalinstan Thanks for the reply.
My requirement is, I have set of HTML 5 assets which needs to be served. 
There are some requests for which the request type is HEAD and getting the 404 error.
I have added the route for all HTTP methods as follows. 
in Obj C:
`[self.server add:^(CRRequest * _Nonnull request, CRResponse * _Nonnull response, CRRouteCompletionBlock  _Nonnull completionHandler) {
       completionHandler();
    }];`

Whats the part I'm still missing.

**Comment by chillin0531** [comment]
Any updates @thecatalinstan

**Comment by chillin0531** [comment]
I could able to find a fix for this problem. 
After adding a route for head request as follows resolves my issue.
`[self.server add:@"/" block:^(CRRequest * _Nonnull request, CRResponse * _Nonnull response, CRRouteCompletionBlock  _Nonnull completionHandler) {
        [response send:@""]; 
        completionHandler();
    } recursive:YES method:CRHTTPMethodHead];`
    
   It works only when a response is sent.
