### ISSUE TITLE
Broken pipe socket error. Any config options for specifying timeout? Other solutions?

### ISSUE THREAD

**Issue by joshhensley** [thecatalinstan/Criollo#13]
I am using Criollio as HTTP Server on iOS with a POST endpoint that accepts large image files encoded as string in JSON body of request. This works for the most part, but I have encountered failing requests with a socket error "broken pipe"

Any ideas what might be going on?

**Comment by thecatalinstan** [comment]
Hi @joshhensley, thanks for using Criollo.  You can set many configuration options in the main bundle's Info.plist file. I believe the one that will take care of your issue is called `CRConnectionKeepAliveTimeout`. It's in seconds. The default is 15 in order to defend agains SlowLoris attacks.

For a full list of server configuration options, look at CRHTTPConnection, CRHTTPServerConfiguration and CRServerConfiguration. 

Apologies for the piss poor documentation job. It's a work in progress.

**Comment by thecatalinstan** [comment]
@joshhensley, did it help?

**Comment by joshhensley** [comment]
Success! I set various timeout keys from CRHTTPServerConfiguration to more appropriate values for my use cases and all is good. Thanks for your help! Marking closed.

**Comment by thecatalinstan** [comment]
That's great to hear. Also, one more thing:

For now, JSON requests are parsed atomically, i.e. after the entire request body has been received.  It is conceivable in your use case that someone could crash the app by simply uploading a huge image, thus hitting iOS' memory limit, forcing the OS to shut down the app.

I would use two requests in your scenario:

1. A JSON request to send the _entity_ details
2. A mime/multipart request to actually upload the image

Mime requests are parsed as a stream, i.e. as they come and are much more efficient. Once the request is parsed, you will be able to access the files in the `request.files` property and the other fields in the request through the `request.body` property.  `request.files` is an array of [`CRUploadedFile`](https://github.com/thecatalinstan/Criollo/blob/master/Criollo/Source/CRUploadedFile.h) objects.
