### ISSUE TITLE
Is it possible to make workerQueue of CRServer public?

### ISSUE THREAD

**Issue by levey** [thecatalinstan/Criollo#27]
I think some user may need to control the max concurrent operation count as iOS has the thread count limit.

**Comment by thecatalinstan** [comment]
Hey @levey,

I think that's a valid point. I'll think about it. Another option would be adding configuration options to control the queue behaviour. I don't know yet which is best. I'll have to give it some thought.

In the meantime, you can achieve the functionality as follows:

**Method 1: Class extension to CRServer** 

```obj-c
@interface CRServer ()

@property (nonatomic, strong) NSOperationQueue* workerQueue;

@end
```

You don't need to actually implement anything, because `workerQueue` is implemented in `CRServer.m`. This just lets the compiler know that there is a property.

**Method 2: KVC (`valueForKey:`)**

```obj-c
CRServer *server; // your server instance
...
NSOperationQueue *queue = (NSOperationQueue *)[server valueForKeyPath:@"workerQueue"];
```
Hope this helps :)

PS: As far as I remember, your app was Objective-C. Method 2 should work on Swift as well.

**Comment by thecatalinstan** [comment]
Hey @levey, did it work?

**Comment by levey** [comment]
@thecatalinstan implicit but work!
