### ISSUE TITLE
Swift Package Manager Support

### ISSUE THREAD

**Issue by jhoughjr** [thecatalinstan/Criollo#28]
I attempted to integrate this using SPM, which often has worked with GitHub dependencies that didnt explicitly support it, but it doesn't seem to work.
It could be that I just updated Xcode and something is broken though.

**Comment by thecatalinstan** [comment]
Hey @jhoughjr, was that it?

**Comment by thecatalinstan** [comment]
Hi @jhoughjr,

I've been looking into this a bit and there are two impediments to adding "proper" SPM support at the time:

**1. `CocoaAsyncSocket` as a submodule**

I want to be able to support manual integration, CocoaPods and Carthage, apart from SPM, with vey little effort from the part of the developer. In order to do this, CocoaAsyncSocket is added as a submodule, so that (1) developers don't have to go and manually download it and place it into the correct folder and (2) I can control which version is supported. 

Unfortunately, from what I have seen, SPM seems to download the submodules as well, so I can't specify it as a dependency in `Package.swift` without anding up with duplicate code. This is not a show stopper, at all, but rather falls into the _not-so-nice_ category.  I am working on removing the dependency on CocoaAsyncSocket altogether, so this would anyway be a temporary issue.

What _is_ however a show stopper is the following:

**2. `OpenSSL` as a binary dependency**

OpenSSL is included in order to provide the ability to parse DER and PEM certificates and private key pairs on iOS and tvOS, where this is not supported natively. OpenSSL is, however not very easy to build on these platforms, so I made the choice to provide a precompiled version of it in the form of a framework on iOS and a static library on tvOS. 

SPM does not support binary packages at the time of writing.

I was considering removing the dependency on OpenSSL (and DER and PEM support on iOS) but I have not made a decision yet. Until either OpenSSL is removed as a binary dependency or SPM supports binary packages, providing an SPM package will be impossible.

SPM support will have to be revisited at a later time.

**Comment by thecatalinstan** [comment]
Since the OpenSSL dependency has been removed in `4ea09fb71a47b52255c0c0a9d31fa1bda2d475e9`, I can give this another shot.
