### ISSUE TITLE
Async code in CRViewController 

### ISSUE THREAD

**Issue by FreakTheMighty** [thecatalinstan/Criollo#31]
I have a list of items that I fetch asynchronously from a database.  How would you recommend handling async requests within `func present(with request: CRRequest, response: CRResponse) -> String`?

**Comment by thecatalinstan** [comment]
Hi @FreakTheMighty,

The basic idea is not to return from the function before you have the complete string you want to return.

The details of the implementation will vary highly, depending on the mechanism you use for running async. But the general idea is to construct your string fully and then return it from this function, so that the controller will display it.

To achieve this, we have to block the thread that's running the `present` function until the async execution completes. One of the easiest ways of doing this is to use a [dispatch semaphore](https://developer.apple.com/documentation/dispatch/dispatchsemaphore). The work-flow would be pretty straight forward:

1. Create the semaphore
2. Launch _async_ work
3. Tell the semaphore to`wait` (this blocks the calling thread until it's signaled)
4. When the _async_ work completes (on a different thread) `signal` the semaphore
5. Return the string

There is a nice guide on semaphores [here](https://medium.com/swiftly-swift/a-quick-look-at-semaphores-6b7b85233ddb).

That being said, you don't really _need_ to send your database work async, since Criollo can handle multiple concurrent requests without blocking them. This means that there is little real benefit of running your database queries async.

Hope this helps.

**Comment by FreakTheMighty** [comment]
Thanks @thecatalinstan that was the solution I arrived at myself, its good to know thats the best practice. Thanks for the quick response!

**Comment by thecatalinstan** [comment]
Glad I could help 👍
