### ISSUE TITLE
File server can throw unhandled exceptions if content changes

### ISSUE THREAD

**Issue by mr-fixit** [thecatalinstan/Criollo#35]
Steps:
- build and run 'Criollo macOS App'
- create a file called 'fileA', bigger than `CRStaticFileServingReadThreshold` (512KB) in $HOME.
- in Terminal (I use Bash, if it matters), execute 
    `while true; do cp fileA fileB; sleep .01; rm fileB; sleep .01;  done`

- open more Terminal windows, in each, execute 
    `while true; do curl -sS http://192.168.0.5:10781/pub/fileB > /dev/null; sleep .0099; done`

After a short time, you’ll hit one of the following uncaught exceptions:

 1) “Response is already finished”

```
    2019-01-26 17:35:05.533456-0500 Criollo macOS App[65524:10014316] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Response is already finished'
    *** First throw call stack:
    (
	0   CoreFoundation                      0x00007fff51520ecd __exceptionPreprocess + 256
	1   libobjc.A.dylib                     0x00007fff7d5ec720 objc_exception_throw + 48
	2   Criollo                             0x00000001003b1919 -[CRHTTPResponse writeData:finish:] + 137
	3   Criollo                             0x000000010037ea94 -[CRResponse sendString:] + 100
	4   Criollo                             0x000000010037cf31 __47+[CRRouter errorHandlingBlockWithStatus:error:]_block_invoke + 1585
	5   Criollo                             0x00000001003aff3c __49+[CRStaticFileManager errorHandlerBlockForError:]_block_invoke + 444
	6   Criollo                             0x00000001003afb47 __127+[CRStaticFileManager servingBlockForFileAtPath:fileName:contentType:contentDisposition:fileSize:shouldCache:fileReadingQueue:]_block_invoke.182 + 935

```
2) “index 0 beyond bounds for empty array”

```    2019-01-28 08:47:00.821191-0500 Criollo macOS App[79277:347935] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array'
    *** First throw call stack:
    (
	0   CoreFoundation                      0x00007fff2b484ecd __exceptionPreprocess + 256
	1   libobjc.A.dylib                     0x00007fff57550720 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff2b4c44a0 -[CFPrefsConfigurationFileSource initWithConfigurationPropertyList:containingPreferences:] + 0
	3   CoreFoundation                      0x00007fff2b3bf397 -[__NSArrayM objectAtIndex:] + 151
	4   Criollo                             0x0000000100373ee4 -[CRConnection sendDataToSocket:forRequest:] + 116
	5   Criollo                             0x000000010039c919 -[CRHTTPResponse finish] + 233
	6   Criollo                             0x000000010039a83f __127+[CRStaticFileManager servingBlockForFileAtPath:fileName:contentType:contentDisposition:fileSize:shouldCache:fileReadingQueue:]_block_invoke_2 + 655
	7   libdispatch.dylib                   0x00000001004046eb _dispatch_call_block_and_release + 12
```

**Comment by thecatalinstan** [comment]
Hi @mr-fixit ,

Great to see the interest in Criollo. I never thought about using it the way you are doing, so it's really cool to see someone using it to _do_ stuff.

That being said, let's take the two exceptions one by one:

**1. Response is already finished**

This is thrown on purpose. One should never get into a state where data is being sent after the response has finished.  It's meant to point out application logic errors. _(Even if the application is the framework itself :))_.

We should leave it as it and instead look at why it gets there in the first place. The implementation for serving large static files uses `dispatch_io_channel` and there is a lot of _async_ happening there, so most likely a weird racing condition is the culprit. 

I'll look into why/how this is and get back to you. Time is, unfortunately, a scarce commodity these days, so please bare with me. In the meantime, feel free to look into it. I have also made a  few comments on your pull request (#36). Thanks, by the way for taking the time to actually look at what is happening.

**2. Index 0 out of bounds**

I have seen this sporadically in various scenarios, mostly on older releases on macOS. I think you are on the right track with the changes in the pull-request. Although I am not 100% sure, my previous investigations also lead me to the `requests.firstRequest` part. I was never able to consistently reproduce it though. I made a comment on the changes you suggested. 

We'll have to look at it a bit more to see if that is what actually causes it, or if it's a dummy that the dynamic nature of ObjC is throwing at us. The reason I'm saying this is because of item 2 in the call stack:

```
	2   CoreFoundation                      0x00007fff2b4c44a0 -[CFPrefsConfigurationFileSource initWithConfigurationPropertyList:containingPreferences:] + 0
```

I would love to get a clear understanding of why this gets called. :)
