### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by keniwhat** [thecatalinstan/Criollo#37]
This HTTP server has a lot of potential.    CocoaHTTPServer by Robbie Hanson hasn't had a commit in 4 years.   GCDWebServer does not do HTTPS.  The Swift servers (Perfect, Vapor, Kitura) are overkill and Swift package manager, Xcode projects and carthage don't live well together, at least until ABI stability comes to Swift.

What is missing here (for me), is authentication. But, by adding a route for all URLs, authentication can be done as a filter.  If the authentication fails, executing the following code will cause the error to be sent.
   [response setStatusCode:403 description:@"Forbidden"];
   [CRRouter errorHandlingBlockWithStatus:403 error:error](request, response, completionHandler);
This protects the resource, but is not strictly correct as 401 should be sent with a challenge.

In the path handler (controller) the response can be interrogated and the response skipped. If this is not done executing completionHandler() again causes an exception as the response has already bee sent.
    if (response.statusCode == 200)
    {
         // Handle response
         completionHandler();
    }

This pattern fails for Static File and Directory Handling but can be fixed using by not executing the code in 'servingBlockForFileAtPath' and 'indexBlockForDirectoryAtPath' with a simple test:
    if (response.statusCode == 200)
        return;

The generic solution  is probably ignoring ALL routes if statusCode is not 200.

The complete solution is to send  401 with a challenge.

Is this something that is on the road map?

Thanks,
Ken Carroll

**Comment by thecatalinstan** [comment]
A million apologies for the (extremely) late response. Due to personal reasons I've been away from this and other projects for a while.

I just wanted to let you know how much I appreciate your input. It shows that you actually have dived a bit in the guts of this little project.

That's a very well spotted flaw in the error handling pattern. I did have it on the back of my mind to do something about the static route controllers in order to allow them to play nicer with the routing model. I think the issue will affect all routes which are declared as `recursive`.

Just to let you know, if it wasn't on the "roadmap", it definitely is now.

Thanks you so much for the kind words and for using Criollo.

All my best,
Cătălin

**Comment by thecatalinstan** [comment]
Hi @keniwhat ,

I've been looking into this and I think it can be achieved with the current setup. I've added the [HTTPAuthentication](https://github.com/thecatalinstan/Criollo/tree/master/Examples/HTTPAuthentication) example that showcases basic HTTP authorization with a 401 status code and a challenge. The main idea is to stop processing the route if authorization fails, the rest is fluff.

Below are a few thoughts on your initial post.

> ```objc
> [response setStatusCode:403 description:@"Forbidden"];
> [CRRouter errorHandlingBlockWithStatus:403 error:error](request, response, completionHandler);
> ```
> This protects the resource, but is not strictly correct as 401 should be sent with a challenge.

Indeed a `401` is more suitable, but those responses don't require a body, so sending a `Content-Length: 0` header should be enough. Also, fyi `CRRouter`'s `+errorHandlingBlockWithStatus:error:` is provided as a sort of generic error handler and it will probably be removed from the public API.

> In the path handler (controller) the response can be interrogated and the response skipped. If this is not done executing completionHandler() again causes an exception as the response has already bee sent.
> ```objc
> if (response.statusCode == 200)
> {
>     // Handle response
>     completionHandler();
> }
> ```

I think a much more efficient approach would be to not continue with processing the route (i.e. executing all the blocks) if the authentication fails. The _filter_ block should not call its `CRRouteCompletionBlock` . This un-complicates the logic in the subsequent blocks and also ensures that, the blocks can _do their job_ once they are invoked. 

That was the whole idea when designing it this way (chaining blocks onto a route) instead of making it a _handle request, return response_ type API: giving the app the freedom to "shape" the execution path at runtime.

> This pattern fails for Static File and Directory Handling but can be fixed using by not executing the code in 'servingBlockForFileAtPath' and 'indexBlockForDirectoryAtPath' with a simple test:
> ```objc
> if (response.statusCode == 200)
>     return;
> ```

The complete solution is to send 401 with a challenge.
I'm not a fan of having components such as the `CRStaticDirectoryManager` and the `CRStaticFileManager` _know_ and _decide_ too much about the rest of the logic. They are the sort of components that will finalize the response so, when they are called, they will do what they do best: serve their respective content. The idea is to not let the request handling reach these components in the first place. IMHO they should be focusing on doing their own tasks and not making decisions about when to do it :)

> The generic solution is probably ignoring ALL routes if statusCode is not 200.

I think this logic belongs to the implementation, not the framework. As above, I think the various components should not make too many decisions and knowing too much about what is going on around them.

---

Those are my two cents, I hope you found my comments and the example, even if it came a million years later. Sorry about that. Thanks for using Criollo and feel free to reach out.

Best,
Cătălin
