### ISSUE TITLE
"This site can't be reached" after multipart file upload

### ISSUE THREAD

**Issue by godexsoft** [thecatalinstan/Criollo#48]
This is more of a question than a report since it actually works fine for most users. But some users report that when they upload a file into the app they _most of the times_ get "Can't be reached" error page from the browser. I have tried the same files they upload, big and small but it always works correctly for me. Any ideas why this could theoretically be happening to some users? Could it be an error in Criollo? Maybe something specific in their setup? The use is always the same - an embedded webserver in my iOS app that users access from their PC. It provides a form to upload a zip file and handles the upload, unzip etc. Nothing crazy and nothing that should be throwing any errors really. Also, it's in Objective-C, not swift. Any ideas and pointers are welcome. Been trying to figure it out for a while now. Thanks!

EDIT: forgot to mention that the error is *ERR_CONNECTION_RESET*

**Comment by thecatalinstan** [comment]
Hi @godexsoft,

First of all apologies for getting back to you so late. Personal reasons have not allowed me to spend much time on projects like Criollo lately.

In the hope that this will help, here's my two cents. I'm not sure who/what can cause this as it can be caused by any actor in the network stack: browser, networking on client's machine, proxy, networking on server (the iOS device), web app (Criollo or something else in the logic). However, since you have not been seeing this in various testing scenarios and that _it's always the same user_ it would strongly seem to suggest that there should be something particular about their setup. 

The only Criollo related cause I can think of is that Criollo closes the connection if the request is not finished in a timely fashion, 15 sec by default. This is a feature, and the timeout can be controlled by setting the value of the `CRConnectionKeepAliveTimeout` in your app's `Info.plist` to a larger value, as shown below (see issue #13 for more details). Maybe they're uploading a large file and their connection isn't stellar. 

```XML
<key>CRConnectionKeepAliveTimeout</key>
<integer>300</integer> <!-- timeout in seconds -->
```

It would be nice to have access to their device so that you can see what Criollo is _doing_, just to rule out an error on that side, but ...

**Comment by godexsoft** [comment]
Hi @thecatalinstan , thanks for the reply :)

It was indeed a firewall issue for some of the users. Typically they are using windows and microsoft's defender is configured somehow to block certain requests.. probably it's thinking that we are trying to upload something we should not (think keylogger?). Eitherway, disabling defender solves the issue for these users so it's not Criollo's fault.

Cheers,
Alex

**Comment by thecatalinstan** [comment]
Awesome, happy to hear an explanation has been found. 👍
