### ISSUE TITLE
HTTP keep-alive connections

### ISSUE THREAD

**Issue by chaitanyabaranwal** [thecatalinstan/Criollo#65]
Hi there! I am trying to use `CRHTTPServer` as a reverse proxy and was trying to decide between using Criollo or the very popular [GCDWebServer](https://github.com/swisspol/GCDWebServer). Unfortunately, GCDWebServer does not support keep-alive connections (even though it uses HTTP/1.1) so was wondering if Criollo does support it. Would really help me out in making a decision, thank you!

**Comment by thecatalinstan** [comment]
Hi @chaitanyabaranwal,

Thanks for considering Criollo! Short answer is _yes_. :) 

Criollo will respect the value of the connection header sent by the client and if no `Connection` header is specified, it will default to `keep-alive` for HTTP/1.1 and `close` for HTTP/1.0 (see  [`CRRequest shouldCloseConnection`](https://github.com/thecatalinstan/Criollo/blob/fd3569ef74f6e1f83ac76125008322e62784d8eb/Criollo/Source/CRRequest.m#L126-L137).  If it doesn't, it's a bug. I should also mention that Criollo also supports HTTP request pipelining if your upstream could use such a feature. You don't have to do anything to use it, it is just _there_.

If you are considering having this as a long-running service on a machine - as opposed to embedding it in a Cocoa or iOS/tvOS app - Criollo plays quite nice with this scenario. In fact that's the primary scenario I built it for :). The [Hello World Example](https://github.com/thecatalinstan/Criollo/tree/master/Examples/HelloWorld) shows how to use `CRApplication` and `CRApplicationDelegate` to accomplish this and I wrote a [blog post](https://criollo.io/blog/2017/01/making-your-first-criollo-app) a while back that details the whole process. You could then create a `launchd.pilst` in order to spawn the service via `launchd`. The [Criollo Website](https://github.com/thecatalinstan/Criollo-Web) is, in fact, setup to run like this (see its [launchd.plist](https://github.com/thecatalinstan/Criollo-Web/blob/master/Criollo%20Web/io.criollo.Criollo-Web.plist)).

Finally, I'd like to say that your project sounds quite exciting. I'd love to hear how it goes. Please write if there is anything else I can help with.

Best,
Cătălin

**Comment by chaitanyabaranwal** [comment]
Hey @thecatalinstan, thanks for the prompt reply! Really appreciate it :)

**Comment by thecatalinstan** [comment]
Don’t metion it! Happy to help.
