### ISSUE TITLE
Don't understand why iOS development target version was upgraded to 12

### ISSUE THREAD

**Issue by tepmnthar** [thecatalinstan/Criollo#86]
My project is currently using version 1.0.1. And recently after I imported another pod that also contains OpenSSL static library, I had duplicate symbols compilation errors. So I'm looking for some workaround to solve it. Then I found that you had already remove the OpenSSL dependency in the newest commits. I'm using p12 file for HTTPS server, so there's no difference for me. 

The only problem is my project supports from iOS 9.0, while your newest commits([fcb224](https://github.com/thecatalinstan/Criollo/commit/fcb224a1e301d4b8845f1db902e2137fa117fa92)) change the iOS development target to 12. I don't understand why and I suppose that you have upgraded some dependencies which require iOS 12.

This is my current workaround, I have only cherry-picked commits from this branch(feature/#69-remove-openssl) to the old stable 1.0.1 ([4605788](https://github.com/thecatalinstan/Criollo/commit/46057887fafd1f6454f9bcbcbde504428b5366b0)), nothing else included. Everything seems to work after tests. No compilation errors, no functional errors, nothing wrong. 

But still, I don't know why the iOS development target version was upgraded. Did I miss something? Just want to check that remove OpenSSL from version 1.0.1 will not cause any problem.

**Comment by thecatalinstan** [comment]
Hi @tepmnthar,

It was for compatibility with current Xcode versions. I hate seeing that kind of stupid warning in my project. There is no practical reason. There's nothing in there that doesn't work on iOS 9. Technically, if it weren't for NSOperationQueue, Criollo's requirements are the same as GCDAsyncSocket's, for now.

I think you can safely set the deployment target to 9.0.

I'll try to get my stuff together and put the next release out sooner rather than later, but there's a lot of work left to do and I have a lot of stuff going on atm, so I can't really say _when_.

Some of the stuff I plan to put in are: eliminating all dependencies, refactoring of the class structure to allow for more protocols to be added easily and some more performance improvements and the like.

Hope this helps.

Best,
Catalin

**Comment by tepmnthar** [comment]
Hi @thecatalinstan, thanks for the reply!

Checked. 👍
Very glad to hear that the new version is coming.

**Comment by leszek-s** [comment]
@thecatalinstan Do you plan perhaps to release a version based on latest 1.0.1 release but with OpenSSL removed, without other changes recently made? I guess that you plan to make a new release after other stuff which is currently in progress is finished but such version only without OpenSSL would also be useful.

**Comment by sanjaneya-chwy** [comment]
@thecatalinstan -- Is there a release version available without openSSL? using Criollo is running into the open SSL issue when running on m1 macbooks. Please provide an update, would greatly appreciate it. I opened an issue for it too: https://github.com/thecatalinstan/Criollo/issues/92
